#!/bin/bash
# This entrypoint runs envsubst on the config file passed as argument
# e.g.
#   envoy -c /etc/envoy/envoy.yaml
# will run
#   envsubst /etc/envoy/envoy.yaml | envoy -c /dev/fd/1
set -euo pipefail

function get_envoy_config {
  if test -f "/etc/envoy.yaml"; then
    echo /etc/envoy.yaml
  elif test -f "/etc/envoy/envoy.yaml"; then
    echo /etc/envoy/envoy.yaml
  elif test -f "/etc/envoy/envoy.json"; then
    echo /etc/envoy/envoy.json
  elif test -f "/home/envoy/envoy.yaml"; then
    echo /etc/envoy/envoy.yaml
  elif test -f "/home/envoy/envoy.json"; then
    echo /etc/envoy/envoy.json
  else
    echo /etc/envoy.yaml
  fi
}

SRC_FILE=
DST_FILE=
if [ $# -eq 0 ]; then set -- "-c" "$(get_envoy_config)"; fi
if [[ "$1" == -* ]]; then set -- "envoy" "$@"; fi
if [[ "$1" != "envoy" ]]; then exec "$@"; fi

ARGS=( "$@" )
for (( i=0; i<${#ARGS[@]}; i++ ));
do
  if [[ "${ARGS[$i]}" == "-c" ]] || [[ "${ARGS[$i]}" == "--config-path" ]]; then
    SRC_FILE="${ARGS[$i+1]}"
    DST_FILE="/tmp/$(basename "$SRC_FILE")"
    ARGS[$i+1]="$DST_FILE"
    i=$((i+1))
  fi
done

if [[ "$SRC_FILE" != "" ]] && ! test -f "$SRC_FILE"; then
  >&2 echo "Envoy config file not found: $SRC_FILE"
  exit 1
fi

set -- "${ARGS[@]}"
if [[ "$SRC_FILE" != "" ]]; then
  envsubst < "$SRC_FILE" > "$DST_FILE"
  >&2 echo "Envoy config file generated: $DST_FILE"
  >&2 echo "Envoy starting with: $@"
  exec "$@"
else
  >&2 echo "Envoy starting with: $@"
  exec "$@"
fi
