---
kind: pipeline
name: build

steps:
- name: docker-node
  image: livingdocs/docker-node
  pull: always
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: ^docker-node/
    context: ./docker-node
    dockerfile: ./docker-node/Dockerfile
    repo: livingdocs/docker-node

- name: postgres-exporter
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: ^postgres-exporter/
    context: ./postgres-exporter
    dockerfile: ./postgres-exporter/Dockerfile
    repo: livingdocs/postgres-exporter

- name: certbot-route53-postgres
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: certbot-route53-postgres.Dockerfile
    dockerfile: certbot-route53-postgres.Dockerfile
    repo: livingdocs/certbot-route53-postgres

- name: odyssey
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: ^odyssey/
    context: ./odyssey
    dockerfile: odyssey/Dockerfile
    repo: livingdocs/odyssey

- name: blackbox-exporter
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: ^blackbox-exporter/
    context: ./blackbox-exporter
    dockerfile: ./blackbox-exporter/Dockerfile
    repo: livingdocs/blackbox-exporter

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [push]
---
kind: signature
hmac: f25ae1c3d01707be25e4f57d119f898e385a18640dfdc92c7225fd686a6b5ddf

...
