---
kind: pipeline
name: build

steps:
- name: docker-node
  image: livingdocs/docker-node
  pull: always
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: ^docker-node/
    context: ./docker-node
    dockerfile: ./docker-node/Dockerfile
    repo: livingdocs/docker-node

- name: postgres-exporter
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: ^postgres-exporter/
    context: ./postgres-exporter
    dockerfile: ./postgres-exporter/Dockerfile
    repo: livingdocs/postgres-exporter

- name: certbot-route53-postgres
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: certbot-route53-postgres.Dockerfile
    dockerfile: certbot-route53-postgres.Dockerfile
    repo: livingdocs/certbot-route53-postgres

- name: node-12
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  settings:
    whenChanged: node-12.Dockerfile
    dockerfile: node-12.Dockerfile
    repo: livingdocs/node

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [push]
---
kind: signature
hmac: 9571ef94cda179423d7913185aca608cc6e863c26441bad9e93a8f3f23dd166a

...
