# docker build -t livingdocs/node:12.0 - < Dockerfile.node
FROM node:12-alpine
RUN apk add --no-cache curl git tini nano
WORKDIR /app
ENV NPM_CONFIG_LOGLEVEL warn
ENV PATH $PATH:/app/node_modules/.bin
ENTRYPOINT ["/sbin/tini", "--"]
