# https://hub.docker.com/_/docker
FROM docker:19
# Docker is based on alpine 3.10
# This distribution includes node 10: https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.10
RUN apk add --no-cache git curl nodejs npm
