#!/bin/bash
if [ "$PLUGIN_CREDENTIALS" ]; then
  PLUGIN_USERNAME=$(jq -r '.username' <<< "$PLUGIN_CREDENTIALS")
  PLUGIN_PASSWORD=$(jq -r '.password' <<< "$PLUGIN_CREDENTIALS")
else
  PLUGIN_USERNAME="${PLUGIN_USERNAME:-${DOCKER_USERNAME:-}}"
  PLUGIN_PASSWORD="${PLUGIN_PASSWORD:-${DOCKER_PASSWORD:-}}"
fi
if [ "${PLUGIN_USERNAME:-}" ] || [ "${PLUGIN_PASSWORD:-}" ]; then
  OUTPUT=$(echo "$PLUGIN_PASSWORD" | docker login -u="$PLUGIN_USERNAME" --password-stdin 2>&1)
  if [ "$?" != "0" ]; then
    >&2 echo "Failed to set credentials for user $PLUGIN_USERNAME"
    >&2 echo "$OUTPUT"
    exit 1
  else
    >&2 echo "Docker credentials configured for user $PLUGIN_USERNAME"
  fi
else
  >&2 echo "No docker credentials provided"
  >&2 echo "Please provide a DOCKER_USERNAME and DOCKER_PASSWORD environment variables to operate against the registry"
  exit 1
fi
