#!/bin/bash
BEFORE=${DRONE_COMMIT_BEFORE:-}
AFTER=${DRONE_COMMIT_AFTER:-}

if [ "$BEFORE" == "" ] || [ "$AFTER" == "" ]; then
  >&2 echo "The environment variables 'DRONE_COMMIT_BEFORE' and 'DRONE_COMMIT_AFTER' must be defined. Skipping build."
  exit 78
fi

git rev-parse HEAD > /dev/null 2>&1
[ $? -gt 0 ] && >&2 echo "Please run that command in a git directory. Skipping build." && exit 1

FILES_CHANGED=$(git diff $BEFORE $AFTER --name-only)
if [ "$?" != "0" ]; then
  >&2 echo "Please run that command in a git directory. Skipping build."
  exit 78
fi

# A regex pattern
PATTERN="${1:-.*}"
FILTERED_FILES=($(grep -E "$PATTERN" <<< "$FILES_CHANGED"))
FILTERED_COUNT=${#FILTERED_FILES[@]}

if [ $FILTERED_COUNT -eq 0 ]; then
  >&2 echo "Skipping the build as no file changed."
  exit 78
else
  >&2 echo "Triggering the build as $FILTERED_COUNT files changed:"
  >&2 echo "----------------------------------------------"
  >&2 printf '%s\n' "${FILTERED_FILES[@]:0:9}"
  [ $FILTERED_COUNT -gt 9 ] && >&2 echo "... and $((FILTERED_COUNT - 9)) more"
  >&2 echo "----------------------------------------------"
  exit 0
fi
